CREATE DATABASE oscontrol;

USE oscontrol;

CREATE TABLE clientes (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
telefone VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
documento VARCHAR(100) NOT NULL,
endereco VARCHAR(100) NOT NULL,
senha VARCHAR(500) NOT NULL,
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE veiculos (
id INT PRIMARY KEY AUTO_INCREMENT,
id_cliente INT,
FOREIGN KEY(id_cliente) REFERENCES clientes(id),
modelo VARCHAR(50) NOT NULL,
marca VARCHAR(50) NOT NULL,
ano VARCHAR(50) NOT NULL,
placa VARCHAR(50) NOT NULL,
observacoes VARCHAR(150),
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE mecanicos (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
especialidade VARCHAR(100) NOT NULL,
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE os (
id INT PRIMARY KEY AUTO_INCREMENT,
id_cliente INT,
id_mecanico INT,
FOREIGN KEY(id_cliente) REFERENCES clientes(id),
FOREIGN KEY(id_mecanico) REFERENCES mecanicos(id), 
data_os DATE DEFAULT(CURRENT_DATE()),
status_os VARCHAR(100) NOT NULL,
problema VARCHAR(150) NOT NULL,
diagnostico VARCHAR(150) NOT NULL,
mecanico VARCHAR(100) NOT NULL,
itens_os VARCHAR(100) NOT NULL,
valor_total VARCHAR(100) NOT NULL,
observacoes VARCHAR(150),
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categoria (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL UNIQUE,
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subcategoria (
id INT PRIMARY KEY AUTO_INCREMENT,
id_categoria INT,
FOREIGN KEY(id_categoria) REFERENCES categoria(id),
nome VARCHAR(100) NOT NULL,
UNIQUE (nome, id_categoria),
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pecas (
id INT PRIMARY KEY AUTO_INCREMENT,
id_subcategoria INT,
FOREIGN KEY(id_subcategoria) REFERENCES subcategoria(id),
nome VARCHAR(100) NOT NULL,
quantidade INT DEFAULT 0,
preco DECIMAL(10, 2) DEFAULT 0.00,
localizacao VARCHAR(100) DEFAULT 'Localização a ser Definida.',
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM clientes;

SELECT * FROM veiculos;

INSERT INTO clientes(nome, telefone, email, documento, endereco, senha) VALUES ('Joana', '(85)94754-2233', 'joana@gmail.com', '800.833.333-44', 'rua 77 - Maraponga', '12345');


DB_HOST= localhost
DB_USER= root
DB_PASSWORD= 
DB_NAME= oscontrol
FLASK_SECRET_KEY= 12345678#